blog/urls.py
from django.urls import path

from .views import BlogListView, BlogDetailView, BlogCreateView, BlogEditView, update_like


app_name = 'blog'
urlpatterns = [
    path('all/', BlogListView.as_view(), name='blog_list'),
    path('<slug:slug>/<int:year>/<int:month>/', BlogDetailView.as_view(), name='blog_detail'),
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('like/<slug:slug>/', update_like, name='update_like'),
    path('<slug:slug>/<int:year>/<int:month>/edit/', BlogEditView.as_view(), name='blog_edit'),
]

futureSelf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('letter.urls')),
    path('', include('account.urls')),
    path('blogs/', include('blog.urls')),
    path('tinymce/', include('tinymce.urls')),
]

admin.site.site_header = 'Future Self Admin Portal'
admin.site.site_title = 'Future Self Admin Portal'
admin.site.index_title = 'Admin Portal'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


# Create your models here.
class Blog(models.Model):

    class Status(models.TextChoices):
        PENDING = 'under review'
        PUBLISHED = 'published'

    title = models.CharField(max_length=100, unique=True)
    content = models.TextField()
    slug = models.SlugField(unique=True, max_length=100)
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    date_posted = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='blog/')
    status = models.CharField(max_length=15, choices=Status.choices, default=Status.PENDING)
    liked_by = models.ManyToManyField(User, related_name='likes')

    class Meta:
        ordering = ('-date_posted',)
        
    def __str__(self) -> str:
        return self.title
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:blog_detail', args=[self.slug, self.date_posted.year, self.date_posted.month])
    

blog/forms.py
from django import forms

from tinymce.widgets import TinyMCE

from .models import Blog


# Forms
class BlogForm(forms.ModelForm):
    
    class Meta:
        model = Blog
        fields = ('title', 'content', 'image')
        widgets = {'content': TinyMCE()}

blog/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseForbidden
from django.urls import reverse_lazy
from django.shortcuts import render
from django.utils.text import slugify
from django.utils.decorators import method_decorator
from django.views.generic import ListView, UpdateView, CreateView, DetailView
from django.views.generic.edit import DeletionMixin
from django.views.decorators.http import require_http_methods

from django_htmx.http import HttpResponseClientRedirect

from .models import Blog
from .forms import BlogForm


# Create your views here.
class BlogListView(ListView):

    template_name = 'blog_list.html'
    queryset = Blog.objects.filter(status='published')
    context_object_name = 'blogs_list'
    paginate_by = 10


class BlogDetailView(DeletionMixin, DetailView):

    model = Blog
    template_name = 'blog_detail.html'
    success_url = reverse_lazy('blog:blog_list')
    context_object_name = 'blog'

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        obj = self.get_object()
        if request.user != obj.writer:
            return HttpResponseForbidden()
        messages.success(request, 'Your blog has been deleted!')
        return super().post(request, *args, **kwargs)

    
class BlogCreateView(LoginRequiredMixin, CreateView):

    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('blog:blog_create')
    template_name = 'blog_create.html'
    
    def form_invalid(self, form):
        messages.error(self.request, 'Error in submitting blog!')
        return super().form_invalid(form)

    def form_valid(self, form):
        form.instance.writer = self.request.user
        form.instance.slug = slugify(form.instance.title)
        messages.success(self.request, 'Your post has been submitted for review!')
        return super().form_valid(form)
    

@require_http_methods(["POST"])
def update_like(request, slug):
    blog = Blog.objects.get(slug=slug)
    if not request.user.is_authenticated:
        blog_like_url = f'{blog.get_absolute_url()}#liked_info'
        return HttpResponseClientRedirect(f'/auth/login?next={blog_like_url}')
    if request.user in blog.liked_by.all():
        blog.liked_by.remove(request.user)
    else:
        blog.liked_by.add(request.user)
    blog.save()
    return render(request, 'partials/liked_by.html', {'blog': blog})


class BlogEditView(LoginRequiredMixin, UpdateView):

    model = Blog
    form_class = BlogForm
    template_name = 'blog_edit.html'
    
    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if request.user != obj.writer:
            return HttpResponseForbidden()
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.slug = slugify(form.instance.title)
        messages.success(self.request, 'Changes saved!')
        return super().form_valid(form)
    
    def get_success_url(self):
        obj = self.get_object()
        return obj.get_absolute_url()

blog/templates/blog_create.html
{% extends 'base.html' %}


{% block content %}
{% if messages %}
  {% for message in messages %}
    {% if message.tags == "success" %}
      <div class="alert alert-success alert-dismissble fade show w-50 d-flex align-items-center" role="alert">
        <svg xmlns="http://www.w3.org/2000/svg" width="17" height="17" fill="currentColor" class="bi bi-check-circle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Success:">
          <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
        </svg>
        {{ message }}  😊 
        <button type="button" class="btn-close float-end ms-auto" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% elif message.tags == "error" %}
      <div class="alert alert-danger alert-dismissble fade show w-50 d-flex align-items-center" role="alert">
        <svg xmlns="http://www.w3.org/2000/svg" width="17" height="17" fill="currentColor" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Warning:">
          <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
        </svg>
        {{ message }}  🤕
        <button type="button" class="btn-close ms-auto" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% endif %}
  {% endfor %}
{% endif %}
<h3 class="heading">Write a New Blog</h3>
<div class="form">
  <form action="" enctype="multipart/form-data" method="post" class="form-group-lg">
    {% csrf_token %}
    {{ form.non_field_errors }}
    <div class="my-5">
      <label for="title"></label><br>
      <input name="title" id="title" type="text" {% if form.title.value %} value="{{ form.title.value }}" {% endif %} class="w-50" aria-autocomplete="off" placeholder="Title of your article?">
      <span class="error">{{ form.title.errors }}</span>
    </div>
    <div class="my-5">
      <label for="image"></label><br>
      <input type="file" name="image" id="image" class="w-50"><br>
      <span class="error">{{ form.image.errors }}</span>
    </div>
    <div class="my-5 mx-auto text-center w-100">
      <label for="content"></label><br>
      <div class="blog-txtarea">{{ form.content }}</div>
      <span class="error">{{ form.content.errors }}</span>
    </div>
    <button class="btn btn-primary w-50 my-5">Submit For Review</button>
  </form>
</div>
{% endblock %} 

blog/templates/blog_detail.html
{% extends 'base.html' %}


{% block content %}
{% if messages %}
  <div class="alert alert-success alert-dismissble d-flex align-items-center fade show w-50" role="alert">
    <svg xmlns="http://www.w3.org/2000/svg" width="17" height="17" fill="currentColor" class="bi bi-check-circle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Success:">
      <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
    </svg>
    {% for message in messages %}
      {{ message }}  😊 
    {% endfor %}
    <button type="button" class="btn-close ms-auto float-end" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
{% endif %}
<div class="container-fluid width" style="width: 70%;">
  <h3 class="heading"> {{ blog.title|title }} </h3>   
  <img src="{{ blog.image.url }}" alt="" class="img-fluid rounded mx-auto d-block p-3" height="10" width="360">
  <div id="writer" class="my-3">
    <span>By {{ blog.writer }}</span><br>
    <span>{{ blog.date_posted.date }}</span>
  </div>
  <div style="font-family: Arial, Helvetica, sans-serif;">
    <p>{{ blog.content|capfirst|safe }}</p>
  </div>
  {% if user == blog.writer %}
    <div class="my-5">
      <a href="{% url 'blog:blog_edit' blog.slug blog.date_posted.year blog.date_posted.month %}" class="btn btn-outline-primary">Edit blog</a>

      <button type="button" class="btn btn-outline-danger ms-5" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
        Delete blog
      </button>

      <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h1 class="modal-title fs-5" id="staticBackdropLabel">Delete this blog?</h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <h4> {{ blog.title }} </h4>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-danger">Delete</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  {% endif %}
  <hr>
  {% include "partials/liked_by.html" %}
</div>
{% endblock %}

blog/templates/blog_edit.html
{% extends 'base.html' %}


{% block content %}
<div class="form">
  <h3 class="heading">Edit Your Blog</h3>
  <form action="" enctype="multipart/form-data" method="post" class="form-group-lg">
    {% csrf_token %}
    {{ form.non_field_errors }}
    <div>
      <label for="title"></label><br>
      <input name="title" id="title" type="text" value="{{ form.title.value }}" class="w-50" aria-autocomplete="off" placeholder="Title of your article?">
      <span class="error">{{ form.title.errors }}</span>
    </div>
    <div class="my-5">
      <label for="image"></label><br>
      {{ form.image }}
      <span class="error">{{ form.image.errors }}</span>
    </div>
    <div>
      {{ form.content.errors }}
      <label for="content"></label><br>
      <div class="blog-txtarea">{{ form.content }}</div>
    </div>
    <button class="btn btn-primary w-50">Submit</button>
  </form>
</div>
{% endblock %}

blog/templates/blog_list.html
{% extends 'base.html' %}


{% block content %}
{% if messages %}
  <div class="alert alert-success alert-dismissble d-flex align-items-center fade show w-50" role="alert">
    <svg xmlns="http://www.w3.org/2000/svg" width="17" height="17" fill="currentColor" class="bi bi-check-circle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Success:">
      <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
    </svg>
    {% for message in messages %}
      {{ message }}  👍
    {% endfor %}
    <button type="button" class="btn-close ms-auto float-end" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
  {% endif %}
<div class="width">
  <h3 class="heading">Our Blog</h3>
  {% for blog in blogs_list %}
    <div class="my-5">
      <div class="d-flex p-3">
        <img src="{{ blog.image.url }}" alt="" class="flex-start rounded-4" width="190" height="190">
        <div class="flex-end px-3" style="width: calc(100% - 190px);">
          <a href="{{ blog.get_absolute_url }}"> <h5>{{ blog|title }}</h5></a> 
          <p>{{ blog.content|truncatewords_html:25|safe }}</p>
          <div id="writer">
            <hr class="mb-0">
            <span class="small">
              {% if blog.writer.first_name %}
                {{ blog.writer.first_name }} {{ blog.writer.last_name }}
              {% else %}
                {{ blog.writer.username }}
              {% endif %}
            </span><br>
            <span class="small">{{ blog.date_posted.date }}</span>
          </div>
        </div>
      </div>
    </div>
  {% endfor %}
  {% if is_paginated %}
    <div class="pagination d-block">
      <nav aria-label="Page navigation example" class="fst-italic">
        <ul class="pagination">
          {% if not page_obj.has_next %}
            <li class="page-item"><a href="?page=1" class="page-link">jump to first</a></li>
          {% endif %}
          {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a></li>
          {% endif %}
          {% for page in page_obj.paginator.page_range %}   
            {% if page_obj.number == page %}    
              <li class="page-item"><a class="page-link active" href="?page={{ page }}">{{ page }}</a></li>
            {% endif %}
          {% endfor %}
          {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></li>
          {% endif %}
          {% if not page_obj.has_previous %}
            <li class="page-item"><a href="?page={{ page_obj.paginator.num_pages }}" class="page-link">jump to last</a></li>
          {% endif %}
        </ul>
      </nav>
      <div class="step-links">
        <span class="text-muted fst-italic">{{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</span>
      </div>
    </div>
  {% endif %}
</div>
{% endblock content %}