account/urls.py
from django.urls import path

from .views import delete_account, LoginView, LogoutView, ManageAccountView, SignUpView


# Urls
app_name = 'account'
urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('sign-up/', SignUpView.as_view(), name='signup'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('me/manage/', ManageAccountView.as_view(), name='manage_account'),
    path('me/delete/', delete_account, name='delete_account'),
]

blog/urls.py
from django.urls import path

from .views import BlogListView, BlogDetailView, BlogCreateView, BlogEditView, update_like


app_name = 'blog'
urlpatterns = [
    path('all/', BlogListView.as_view(), name='blog_list'),
    path('<slug:slug>/<int:year>/<int:month>/', BlogDetailView.as_view(), name='blog_detail'),
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('like/<slug:slug>/', update_like, name='update_like'),
    path('<slug:slug>/<int:year>/<int:month>/edit/', BlogEditView.as_view(), name='blog_edit'),
]

futureSelf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('letter.urls')),
    path('', include('account.urls')),
    path('blogs/', include('blog.urls')),
    path('tinymce/', include('tinymce.urls')),
]

admin.site.site_header = 'Future Self Admin Portal'
admin.site.site_title = 'Future Self Admin Portal'
admin.site.index_title = 'Admin Portal'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models

# Create your models here.

account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# Forms
class SignUpForm(UserCreationForm):
    
    username = forms.CharField(max_length=15, min_length=4)
    
    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")
        
    def clean_email(self):
        email = self.cleaned_data["email"]
        user_exists = User.objects.filter(email=email).exists()
        if user_exists:
            raise forms.ValidationError("User with that email address already exists")
        return email


class UpdateUserForm(forms.ModelForm):

    username = forms.CharField(max_length=15, min_length=4)

    class Meta:
        model = User
        fields = ("username", "email")
        
    def clean_email(self):
        email = self.cleaned_data["email"]
        user_exists = User.objects.filter(email=email).exclude(email=email).exists()
        if user_exists:
            raise forms.ValidationError("User with that email address already exists")
        return email

account/views.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView as Login, LogoutView as Logout
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import FormView, View

from .forms import UpdateUserForm, SignUpForm


# Create your views here.
class SignUpView(FormView):

    form_class = SignUpForm
    template_name = 'signup.html'
    success_url = reverse_lazy('letter:my_letters')

    def form_valid(self, form):
        username = form.cleaned_data['username']
        email = form.cleaned_data['email']
        password = form.cleaned_data['password2']
        user = User.objects.create_user(
            username=username, email=email, password=password
        )
        login(self.request, user)
        return super().form_valid(form)


class LoginView(Login):

    template_name = 'login.html'
    success_url = reverse_lazy('letter:my_letters')


class LogoutView(Logout):

    success_url = reverse_lazy('letter:home')
    
    def dispatch(self, request, *args,**kwargs):
        messages.info(request, 'You\'ve been logged out!')
        return super().dispatch(request, *args, **kwargs)


class ManageAccountView(LoginRequiredMixin, View):

    form_class = UpdateUserForm
    template_name = 'manage_account.html'

    def get(self, request):
        user = request.user
        form = self.form_class(instance=user)
        context = {'form': form}
        return render(request, self.template_name, context)
        
    def post(self, request):
        user = request.user
        form = self.form_class(instance=user, data=request.POST)
        context = {'form': form}
        if form.is_valid():
            form.save()
            messages.success(request, 'Changes saved!')
            return redirect(reverse('account:manage_account'))
        messages.error(request, 'Error saving changes!')
        return render(request, self.template_name, context)


@login_required
def delete_account(request, pk):
    user = request.user
    user.delete()
    messages.success(request, 'Account deleted!')
    return redirect('/')

account/templates/login.html
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Futureself | Log in</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <script src="https://unpkg.com/htmx.org@1.8.5" integrity="sha384-7aHh9lqPYGYZ7sTHvzP1t3BAfLhYSTy9ArHdP3Xsr9/3TlGurYgcPBoFmXX2TX/w" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="{% static '/css/style.css' %}">
  {{ form.media }}
  <style>
    body {
      font-family: Arial, sans-serif;
      background-color: #f2f2f2;
    }

    .auth-container {
      width: 30%;
      padding-bottom: 2rem;
      margin: 1rem auto;
      background-color: #fff;
      box-shadow: 0 2px 4px rgba(12, 48, 208, 0.1);
    }

    input[type="email"] {
      width: 100%;
      padding: 10px;
      border-radius: 4px;
      margin-bottom: 20px;
    }
</style>
</head>
<body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  {% if form.non_field_errors %}
    <div class="alert alert-danger alert-dismissble fade show w-50 d-flex align-items-center" role="alert">
      <svg xmlns="http://www.w3.org/2000/svg" width="17" height="17" fill="currentColor" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Warning:">
        <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
      </svg>
      {% for message in messages %} {{ message }} {% endfor %} <a href="" class="alert-link mx-2">Reactivate</a>  🤕
      <button type="button" class="btn-close float-end ms-auto" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  {% endif %}
  <div class="form auth-container">
    <div class="bg-primary text-center py-1">
      <h4 class="heading text-white">Futureself</h4>
    </div>
    <h3 class="heading fs-4">Welcome back</h3>
    <form action="" method="post" class="form-group-lg">
      {% csrf_token %}
      <div class="input-group mx-auto w-100 justify-content-center">
        <label for="username" class="input-group-text">Username</label>
        <input type="text" name="username" id="username" class="border-start">
      </div>
      <div class="input-group mx-auto w-100 justify-content-center">
        <label for="password" class="input-group-text text-center">Password</label>
        <input type="password" name="password" id="password" class="border-start">
      </div>
      <p><a type="button" href="#" data-bs-toggle="modal" data-bs-target="#exampleModal">Forgot password?</a></p>
      <button type="submit" class="btn btn-primary mt-3 w-50">Log In</button>
      <hr class="mx-5 my-3">
      <p>Don't have an account? <a href="{% url 'account:signup' %}">Sign up</a></p>
    </form>
  </div>

  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Reset Password</h1>
          <button type="button" class="ms-2 mt-1 border-0"
          data-bs-toggle="tooltip" data-bs-placement="top"
          data-bs-custom-class="custom-tooltip"
          data-bs-title="A one-time link will be sent to your email to reset your password">
            <i class="bi bi-info-circle"></i>
          </button>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form method="post" action="{% url 'account:password_reset' %}">
            {% csrf_token %}
            <label for="email">Email address</label> <br>
            <input type="email" id="email" name="email" width="150" class="w-100 my-2" required> <br><br>
            <div class="my-0 mx-auto text-center">
              <button type="submit" class="btn btn-outline-primary my-2">Send Link</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  <script>
    const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
    const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))
  </script>
</body>
</html>

account/templates/manage_account.html
{% extends 'base.html' %}


{% block content %}
{% if messages %}
  {% for message in messages %}
    {% if message.tags == "success" %}
      <div class="alert alert-success alert-dismissble fade show w-50 d-flex align-items-center" role="alert">
        <svg xmlns="http://www.w3.org/2000/svg" width="17" height="17" fill="currentColor" class="bi bi-check-circle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Success:">
          <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
        </svg>
        {{ message }}  😊 
        <button type="button" class="btn-close float-end ms-auto" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% elif message.tags == "error" %}
      <div class="alert alert-danger alert-dismissble fade show w-50 d-flex align-items-center" role="alert">
        <svg xmlns="http://www.w3.org/2000/svg" width="17" height="17" fill="currentColor" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Warning:">
          <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
        </svg>
        {{ message }}  🤕
        <button type="button" class="btn-close float-end ms-auto" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% endif %}
  {% endfor %}
{% endif %}
<div class="form user_form">
  <h3 class="heading">Manage Your Account</h3>
  <form action="" method="post" class="form-group-lg">
    {% csrf_token %}
    {{ form.non_field_errors }}
    <div class="input-group mx-auto justify-content-center">
      <span class="input-group-text w-25">Username</span>
      <input type="text" name="username" id="username" value="{{ form.username.value }}" class="border-start"><br>
      <span class="error">{{ form.username.errors }}</span>
    </div>
    <div class="input-group mx-auto justify-content-center">
      <span class="input-group-text w-25">Email Address</span>
      <input type="email" name="email" id="email" value="{{ form.email.value }}" class="border-start"> <br>
      <span class="error">{{ form.email.errors }}</span>
    </div>
    <button type="submit" class="btn btn-primary mt-5">Save changes</button>
  </form>
  <hr class="mx-5">
  <h4>Danger zone</h4>

  <button type="button" class="btn btn-outline-danger m-3" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
    Delete account
  </button>

  <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h6 class="modal-title" id="staticBackdropLabel">Delete your account?</h6>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p> This action cannot be undone. </p>
        </div>
        <div class="modal-footer">
          <form action="{% url 'account:delete_account' %}" method="post">
            {% csrf_token %}
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button class="btn btn-danger">Delete</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

account/templates/signup.html
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Futureself | Log in</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <script src="https://unpkg.com/htmx.org@1.8.5" integrity="sha384-7aHh9lqPYGYZ7sTHvzP1t3BAfLhYSTy9ArHdP3Xsr9/3TlGurYgcPBoFmXX2TX/w" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="{% static '/css/style.css' %}">
  {{ form.media }}
  <style>
    body {
      font-family: Arial, sans-serif;
      background-color: #f2f2f2;
    }

    .auth-container {
      width: 30%;
      padding-bottom: 1rem;
      margin: 1.5rem auto;
      background-color: #fff;
      box-shadow: 0 2px 4px rgba(34, 65, 205, 0.1);
    }
</style>
</head>
<body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  {% if form.non_field_errors %}
    <div class="alert alert-danger alert-dismissble fade show w-50 d-flex align-items-center" role="alert">
      <svg xmlns="http://www.w3.org/2000/svg" width="17" height="17" fill="currentColor" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Warning:">
        <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
      </svg>
      {% for message in messages %} {{ message }} {% endfor %} <a href="" class="alert-link mx-2">Reactivate</a>  🤕
      <button type="button" class="btn-close float-end ms-auto" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  {% endif %}
  <div class="form auth-container">
    <div class="bg-primary text-center py-1">
      <h4 class="heading text-white">Futureself</h4>
    </div>
    <div class="form">
      <h3 class="heading">Create a new account</h3>
      <form action="" method="post" class="form-group-lg">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="input-group mx-auto justify-content-center w-100">
          <label for="username" class="input-group-text">Username</label>
          <input type="text" name="username" id="username" class="border-start">
          <span class="error">{{ form.username.errors }}</span>
        </div>
        <div class="input-group mx-auto justify-content-center w-100">
          <label for="email" class="input-group-text">Email address</label>
          <input type="email" name="email" id="email" autocomplete="new-password" class="border-start">
          <span class="error">{{ form.email.errors }}</span>
        </div>
        <div class="input-group mx-auto justify-content-center w-100">
          <label for="password" class="input-group-text">Password</label>
          <input type="password" name="password1" id="password1" autocomplete="new-password" class="border-start">
          <span class="error">{{ form.password1.errors }}</span>
        </div>
        <div class="input-group mx-auto justify-content-center w-100">
          <label for="password2" class="input-group-text">Re-password</label>
          <input type="password" name="password2" id="password2" autocomplete="new-password" class="border-start">
          <span class="error">{{ form.password2.errors }}</span>
        </div>
        <button type="submit" class="btn btn-primary mt-3 w-50">Sign Up</button>
        <hr class="my-3 mx-5">
        <p>Already have an account? <a href="{% url 'account:login' %}">Login</a></p>
      </form>
    </div>
  </div>
</body>
</html>

    