account/urls.py
from django.urls import path

from .views import delete_account, LoginView, LogoutView, ManageAccountView, SignUpView


# Urls
app_name = 'account'
urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('sign-up/', SignUpView.as_view(), name='signup'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('me/manage/', ManageAccountView.as_view(), name='manage_account'),
    path('me/delete/', delete_account, name='delete_account'),
]

blog/urls.py
from django.urls import path

from .views import BlogListView, BlogDetailView, BlogCreateView, BlogEditView, update_like


app_name = 'blog'
urlpatterns = [
    path('all/', BlogListView.as_view(), name='blog_list'),
    path('<slug:slug>/<int:year>/<int:month>/', BlogDetailView.as_view(), name='blog_detail'),
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('like/<slug:slug>/', update_like, name='update_like'),
    path('<slug:slug>/<int:year>/<int:month>/edit/', BlogEditView.as_view(), name='blog_edit'),
]

futureSelf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('letter.urls')),
    path('', include('account.urls')),
    path('blogs/', include('blog.urls')),
    path('tinymce/', include('tinymce.urls')),
]

admin.site.site_header = 'Future Self Admin Portal'
admin.site.site_title = 'Future Self Admin Portal'
admin.site.index_title = 'Admin Portal'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

letter/urls.py
from django.urls import path

from . import views


app_name = 'letter'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('my/letters/', views.get_my_letters, name='my_letters'),
    path('letters/<uuid:pk>/', views.LetterDetailView.as_view(), name='letter_detail'),
    path('letters/create/', views.LetterCreateView.as_view(), name='create_letter'),
    path('letters/<uuid:pk>/update/', views.update_letter_audience, name='update_letter'),
    path('letters/audience/public/', views.PublicLettersView.as_view(), name='public_letters'),
    path('comment/new/<uuid:letter_id>/', views.get_comment_form),
    path('letters/<uuid:letter_id>/comment/new/', views.post_comment, name='post_comment'),
]

letter/models.py
import uuid

from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone


# Create your models here.
class Letter(models.Model):

    class Audience(models.TextChoices):
        PUBLIC_ANON = 'public, but as anon'
        PRIVATE = 'private'

    id = models.UUIDField(unique=True, primary_key=True, default=uuid.uuid4)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    content = models.TextField()
    delivery_date = models.DateField()
    date_posted = models.DateTimeField(default=timezone.now)
    email_address = models.EmailField()
    audience = models.CharField(max_length=20, choices=Audience.choices)
    delivered = models.BooleanField(default=False)

    class Meta:
        ordering = ('-date_posted',)

    def __str__(self):
        return f'{self.title}'

    def get_absolute_url(self):
        return reverse('letter:letter_detail', kwargs={'pk': self.id})


class Comment(models.Model):
    
    user = models.CharField(max_length=100, null=True)
    comment = models.TextField()
    letter = models.ForeignKey(Letter, on_delete=models.CASCADE)
    parent_comment = models.ForeignKey('self', null=True, on_delete=models.SET_NULL, related_name='replies')
    date_posted = models.DateTimeField(default=timezone.now)
    
    def __str__(self):
        return f'Comment by {self.user if self.user else "Anonymous"}'
    

letter/forms.py
from datetime import timedelta

from django import forms
from django.utils import timezone

from tinymce.widgets import TinyMCE

from .models import Letter, Comment


# Forms
class LetterForm(forms.ModelForm):
    
    class Meta:
        model = Letter
        fields = (
            'title',
            'content',
            'email_address',
            'delivery_date',
            'audience'
        )
        widgets = {'content': TinyMCE(attrs={'cols':75, 'rows': 30})}
       
    def clean_content(self):
        letter_content = self.cleaned_data['content']
        if not letter_content or letter_content == ' ':
            raise forms.ValidationError(r'Can\'t send empty letter.')
        return letter_content

    # def clean_delivery_date(self):
    #     date = self.cleaned_data['delivery_date']
    #     print(date)
    #     now = timezone.now().date()
    #     if date - now < timedelta(days=28):
    #         raise forms.ValidationError('Date should be at least a month from now.')
    #     return date


class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment
        fields = ('user', 'comment')

letter/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, ListView
from django.views.generic.edit import DeletionMixin
from django.views.decorators.http import require_http_methods

from django_htmx.http import HttpResponseLocation

from .forms import LetterForm, CommentForm
from .models import Letter


# Create your views here.
class HomeView(CreateView):

    form_class = LetterForm
    template_name = 'homepage.html'
    success_url = reverse_lazy('letter:my_letters')

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
        

@login_required
def current_user_letters(request):
    travelling = Letter.objects.filter(user=request.user, delivered=False)
    delivered = Letter.objects.filter(user=request.user, delivered=True)
    context = {'travelling_letters': travelling, 'delivered_letters': delivered}
    return render(request, 'my_letters.html', context)


class LetterDetailView(DeletionMixin, DetailView):

    model = Letter
    template_name = 'letter_detail.html'
    context_object_name = 'letter'
    success_url = reverse_lazy('letter:my_letters')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = CommentForm
        return context

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        return super().post(request, *args, **kwargs)
    

def get_comment_form(request, letter_id):
    letter = get_object_or_404(Letter, id=letter_id)
    form = CommentForm()
    context = {'form': form, 'letter': letter}
    return render(request, 'partials/comment_form.html', context)


def post_comment(request, letter_id):
    letter = get_object_or_404(Letter, id=letter_id)
    form = CommentForm(request.POST)
    form.is_valid()
    comment = form.save(commit=False)
    comment.user = f'{request.user}' if request.user.is_authenticated else form.cleaned_data['user']
    comment.letter = letter
    comment.save()
    messages.success(request, 'Comment posted!')
    return HttpResponseLocation(letter.get_absolute_url())


@login_required
@require_http_methods(["POST"])
def update_letter_audience(request, pk):
    letter = get_object_or_404(Letter, id=pk, user=request.user)
    if letter.user != request.user:
        return HttpResponseForbidden
    if letter.audience == 'private':
        letter.audience = 'public, but as anon'
    elif letter.audience == 'public, but as anon':
        letter.audience = 'private'
    letter.save()
    return render(request, 'partials/audience.html', {'letter': letter})


class LetterCreateView(LoginRequiredMixin, CreateView):

    form_class = LetterForm
    template_name = 'create_letter.html'
    success_url = reverse_lazy('letter:create_letter')

    def form_invalid(self, form):
        messages.error(self.request, 'Error creating new letter!')
        return super().form_invalid(form)

    def form_valid(self, form):
        form.instance.user = self.request.user
        messages.success(self.request, "Letter submitted sucessfully!")
        return super().form_valid(form)


class PublicLettersView(ListView):

    context_object_name = 'public_letters'
    template_name = 'public_letters.html'
    queryset = Letter.objects.filter(audience='public, but as anon', delivered=True)
    paginate_by = 10
    

letter/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% block title %} <title>Futureself</title> {% endblock %}
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <script src="https://unpkg.com/htmx.org@1.8.5" integrity="sha384-7aHh9lqPYGYZ7sTHvzP1t3BAfLhYSTy9ArHdP3Xsr9/3TlGurYgcPBoFmXX2TX/w" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="{% static '/css/style.css' %}">
  {{ form.media }}
</head>
<body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <nav class="navbar navbar-expand-lg bg-primary bg-gradient navbar-dark text-white p-2">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'letter:home' %}"> Futureself </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-lg-0">
          <li class="nav-item"><a class="nav-link" href="{% url 'letter:create_letter' %}">✒️ Write a New Letter</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'letter:public_letters' %}">🛋 Read Public Letters</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'blog:blog_list' %}">📒 Blog</a></li>
        </ul>
        <ul class="navbar-nav">
          {% if user.is_authenticated %}
            <li class="nav-item dropdown">
              <div class="btn-group" role="group">
                <button type="button" class="btn text-bg-primary">{{ user.email }}</button>
                <button type="button" class="btn text-bg-primary bg-subtle dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
                  <span class="visually-hidden">Toggle Dropdown</span>
                </button>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'letter:my_letters' %}">✉️ My Letters</a></li>
                  <li><a class="dropdown-item" href="{% url 'blog:blog_create' %}">📝 Write a Blog?</a></li>
                  <li><a class="dropdown-item" href="{% url 'account:manage_account' %}">👤 Manage Account</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" hx-post="{% url 'account:logout' %}" href="">Log out</a></li>
                </ul>
              </div>
            </li>
          {% else %} 
            <li class="nav-item"><a class="nav-link" href="{% url 'account:login' %}">Log In</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'account:signup' %}">Sign Up</a></li>
          {% endif %} 
        </ul>
      </div>
    </div>
  </nav>
  <main>
    <div class="container-fluid p-3">
      {% block content %}
      {% endblock %}
    </div>
  </main>
  <script src="/static/js/comments.js"></script>
</body>
</html>

letter/templates/create_letter.html
{% extends 'base.html' %}

{% block content %}
{% if messages %}
  {% for message in messages %}
    {% if message.tags == "success" %}
      <div class="alert alert-success alert-dismissble fade show w-50 d-flex align-items-center" role="alert">
        <svg xmlns="http://www.w3.org/2000/svg" width="17" height="17" fill="currentColor" class="bi bi-check-circle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Success:">
          <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
        </svg>
        <span>{{ message }}  😊 </span>
        <button type="button" class="btn-close ms-auto float-end" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% elif message.tags == "error" %}
      <div class="alert alert-danger alert-dismissble fade show w-50 d-flex align-items-center" role="alert">
        <svg xmlns="http://www.w3.org/2000/svg" weight="17" height="17" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Warning:">
          <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
        </svg>
        <span>{{ message }} 🤕</span>
        <button type="button" class="btn-close ms-auto float-end" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% endif %}
  {% endfor %}
{% endif %}
<div class="form">
  <h3 class="heading mb-2"> Letter to Your Future Self</h3>
  <form action="" method="post" class="form-group-lg">
    {{ form.non_field_errors }}
    {% csrf_token %}
    <div class="text-start ms-lg-5 w-auto">
      <label for="title"></label><br>
      <input name="title" id="title" placeholder="Subject of your letter" class="w-50" autocomplete="off">
      <span class="error">{{ form.title.errors }}</span>
    </div>
    <div class="d-flex justify-content-evenly">
      <div>
        <label for="content"></label><br>
        {{ form.content }}
        <span class="error">{{ form.content.errors }}</span>
      </div>
      <div class="text-start">
        <div class="mb-5">
          <label for="email"></label><br>
          <input type="email" name="email_address" id="email_address" class="w-100" placeholder="Recipient email address">
          <span class="error">{{ form.email_address.errors }}</span>
        </div>
        <div class="mb-5">
          <label for="delivery_date"></label><br>
          <input type="date" name="delivery_date" id="delivery_date" class="w-100"><br>
          {% if form.delivery_date.errors %}
            <span class="error">{{ form.delivery_date.errors }}</span>
          {% else %}
              <span class="help_text small text-muted">&#9888; Date must be at least a month from now</span>
          {% endif %}
        </div>
        <div class="mb-5">
          <label for="audience">Choose your audience</label><br>
          <span class="radio">
            <input type="radio" class="btn-check" name="audience" id="private" value="private" autocomplete="off">
            <label class="btn btn-outline-primary btn-sm" for="private">Private</label>
          </span>
          <span class="ms-4 radio">
            <input type="radio" class="btn-check" name="audience" id="public" autocomplete="off" value="public, but as anon">
            <label class="btn btn-outline-primary btn-sm" for="public">Public, but anonymous</label>
          </span>
        </div>
        <button class="btn btn-primary w-100 p-2" style="margin-top: 11.6rem;" type="submit">🛫 Send to the Future</button>
      </div>  
    </div>
  </form>
</div>
{% endblock %}

letter/templates/homepage.html
{% extends 'base.html' %}


{% block content %}
{% if messages %}
  {% for message in messages %}
  <div class="alert alert-{{message.tags}} alert-dismissible fade show w-50 d-flex align-items-center" role="alert">
    <svg xmlns="http://www.w3.org/2000/svg" width="17" height="17" fill="currentColor" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Warning:">
      <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
    </svg>
    {{ message }} 🙄
    <button type="button" class="btn-close ms-auto float-end" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  {% endfor %}
{% endif %}
<div class="home d-flex justify-content-evenly">
  <div style="width: 60%;">
    <h2 class="heading text-start mt-3 mb-5"> Welcome to Futureself 🔮 </h2>
    <p> 
      <blockquote class="fs-5">
        <span class="h4 fst-italic">S</span>tart a journey of self-discovery and reflection by sending messages to the you of tomorrow.
        Reflect on your present, set goals, and capture memories - all to be unwrapped in the future. 
        Let your future self be inspired by the who you are today. <br> <br>
      </blockquote>
      <blockquote class="text-muted fst-italic">
        "I love this. I've sent myself 5 letters so far and every year it's a surprise. Because I forget so easily. It turns into such a deep reflective process, that I usually weep and laugh while I write."
      </blockquote>
      - Mona Lisa <br>
      Member since 2022
    </p>
    <div class="my-4">
        Futureself letters are good for
        <ul>
          <li>Setting future goals</li>
          <li>Reliving memories</li>
          <li>Acknowledging self-growth and achievements</li>
        </ul>
        <p class="fst-italic fs-5">Allow us be your personal time capsule, helping you connect with your past and future ⌛</p>
    </div>
  </div>
  <div class="align-self-center text-center mt-5">
    <img src="/static/images/_c451e483-d872-4870-9877-8637eb489b74.jpeg" alt="Letter in motion" width="360" class="img-fluid mt-lg-2">
    <a class="btn btn-outline-primary m-3" href='{% url "letter:create_letter" %}'>Take me to the Future</a>
  </div>
</div>
{% endblock content %}

letter/templates/letter_detail.html
{% extends 'base.html' %}


{% block content %}
{% if messages %}
  <div class="alert alert-success alert-dismissble fade show w-50 d-flex align-items-center" role="alert">
    <svg xmlns="http://www.w3.org/2000/svg" width="17" height="17" fill="currentColor" class="bi bi-check-circle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Success:">
      <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
    </svg>
    {% for message in messages %}
      {{ message }}
    {% endfor %}
    <button type="button" class="btn-close ms-auto float-end" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
{% endif %}
<div class="container-fluid">
  {% if letter.delivered %}
    <div class="heading">
      <span class="text-muted">🚀 Time travelled: {{ letter.date_posted|timesince:letter.delivery_date }}</span> <br>
      <span class="text-muted">{{ letter.date_posted.date }} &rightarrow; {{ letter.delivery_date }}</span><br>
      <h3>A Letter From The Past </h3>	
      {% if user == letter.user %}
        <span class="text-muted"> 📬 Received: {{ letter.email_address }}</span>
      {% endif %}
    </div>
    <div class="width" style="width: 70%;">
      <div class="mb-5">
        <h4> {{ letter.title|title }} </h4>
        <p> {{ letter.content|safe }} </p>
      </div>
      {% if user == letter.user %}
        <div class="my-5">
          <h4>Audience</h4>
          {% include "partials/audience.html" %}
        </div>
        <div class="my-5">
          <h4>Delete</h4>
          <p> This action would delete this letter and cannot be undone. </p>
          <button type="button" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
            Delete
          </button>
          <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"  aria-labelledby="staticBackdropLabel" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="staticBackdropLabel">Delete this Letter?</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                  <h4> A Letter from {{ letter.date_posted.date }} </h4>
                  {{ letter.title|title }}
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                  <button class="btn btn-danger">Delete</button>
                </div>
              </div>
            </div>
          </div>
        </div>
      {% endif %}
      {% if letter.comment_set %}    
        {% if letter.audience == 'public, but as anon' or user == letter.user %}
          <hr class="">
          <h4>{{ letter.comment_set.count }} {{ letter.comment_set.count|pluralize:"Comment,Comments"|title }}
            <button class="float-end link-primary border-0 fs-6 p-1" hx-get="/comment/new/{{ letter.id }}/" hx-target="#commentform" hx-swap="outerHTML">+ Add</button>
          </h4>
          <div id="commentform"></div>
          {% for comment in letter.comment_set.all %}
            <div class="card p-1 mb-3">
              <div class="card-body">
                <div style="font-size: smaller;">{{ comment.user }} <span class="text-muted float-end" style="font-size: smaller;">{{ comment.date_posted|timesince }} ago </span></div>
                <div> > {{ comment.comment }}</div>
                <!-- {% if comment.user == user.username %} <button>Delete</button> {% endif %} -->
              </div> 
            </div>
          {% endfor %}
        {% endif %}
      {% endif %}
    </div>
  {% else %}
    <div class="alert alert-warning w-50" role="alert">
      <svg xmlns="http://www.w3.org/2000/svg" width="17" height="17" fill="currentColor" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Warning:">
        <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
      </svg>
      <span>You can't view or modify this letter until delivered.</span>
    </div>
    <div class="heading blur">
      <span>🚀 Time travelled: Travelling</span> <br>
      <h3>A Letter From The Past </h3>	
      <span>From the past &rightarrow; to the future</span><br>
      {% if user == letter.user %}
        <span> 📬 Received: {{ letter.email_address }}</span>
      {% endif %}
    </div>
    <div class="width">
      <div class="mb-5 blur">
        <h4> LOREM IPSUM DOLOR SIT AMET, CONSECTETUR ADIPISCING ELIT </h4>
        <p> 
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce rutrum nibh sit amet sagittis fermentum. Donec eget dui eu tellus faucibus vehicula. Interdum et malesuada fames ac ante ipsum primis in faucibus. Integer non rutrum odio. Aliquam vitae imperdiet libero, sollicitudin faucibus ipsum. Suspendisse id purus risus. Aliquam consectetur malesuada tempus. Suspendisse potenti. Suspendisse viverra laoreet odio quis aliquet. Proin facilisis malesuada orci tincidunt sollicitudin. Proin varius nec justo a volutpat. Praesent fermentum ligula nec dapibus facilisis. In hac habitasse platea dictumst. Fusce sit amet turpis dictum, pretium mi sit amet, hendrerit metus.

          Curabitur nec dui in nulla mattis lobortis. Aliquam posuere purus et augue rutrum fermentum. Sed viverra tellus mollis, pretium risus in, molestie dolor. Aliquam nec tortor magna. Quisque vel erat id ligula pharetra malesuada. Aliquam erat volutpat. Pellentesque iaculis nibh augue, sed congue nibh dignissim a. Integer posuere, augue at sollicitudin dignissim, mi metus malesuada nulla, sit amet sollicitudin lectus tortor vel urna. In a purus metus. Ut dui enim, egestas in urna quis, tempor efficitur quam.        
        </p>
      </div>
      <div class="mt-5">
        {% if user == letter.user %}
          <h5>Audience</h5>
          {% if letter.audience == "private" %}
            Currently set to: <span class="badge bg-info p-1">{{ letter.audience }} </span> <br>
          {% else %}
            Currently set to: <span class="badge bg-secondary p-1">{{ letter.audience }} </span> <br>
          {% endif %}
        {% endif %} 
      </div>
    </div>
  {% endif %}
</div>
{% endblock %}